### ISSUE TITLE
Exception when adding unique tool action provider to a flow

### ISSUE THREAD

**Issue by NickolausDS** [globus-gladier/gladier#219]
Adding a tool with a unique action provider properly triggers a login, but raises an exception when running the flow: 

```
During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "example_publication_flow.py", line 107, in <module>
    flow = my_gladier_client.run_flow(flow_input=flow_input, label=f'Experiment {experiment.name}')
  File "/Users/nick/globus/aps/gladier-gmca-portal/venv/lib/python3.7/site-packages/gladier/client.py", line 263, in run_flow
    return self.flows_manager.run_flow(flow_input=combine_flow_input, **flow_kwargs)
  File "/Users/nick/globus/aps/gladier-gmca-portal/venv/lib/python3.7/site-packages/gladier/managers/flows_manager.py", line 391, in run_flow
    self.refresh_flows_client()
  File "/Users/nick/globus/aps/gladier-gmca-portal/venv/lib/python3.7/site-packages/gladier/managers/flows_manager.py", line 182, in refresh_flows_client
    return self.flows_client
  File "/Users/nick/globus/aps/gladier-gmca-portal/venv/lib/python3.7/site-packages/gladier/managers/flows_manager.py", line 165, in flows_client
    authorizers = self.login_manager.get_manager_authorizers()
  File "/Users/nick/globus/aps/gladier-gmca-portal/venv/lib/python3.7/site-packages/gladier/managers/login_manager.py", line 43, in get_manager_authorizers
    raise AuthException('Manager Failed to produce '
gladier.exc.AuthException: Manager Failed to produce authorizers for missing scopes: {'https://auth.globus.org/scopes/88f79869-f682-4c26-bcbc-db1512e4e791/flow_88f79869_f682_4c26_bcbc_db1512e4e791_user'}
```

This is almost certainly a failure to purge the old client and create a new one with the newly minted tokens. Re-running the flow results in successful run, where it likely creates a brand-new client with the new tokens.

**Comment by NickolausDS** [comment]
Fixed with #271 and #268
